// Critical validation of the SpeakX CAC RCA report — confidence scores,
// issues, spot-checks, and required caveats. Generated by the data-validation
// pass run on 2026-04-29.

export const validationMeta = {
  verdict: "Share with noted caveats",
  verdictTone: "warn" as const,
  date: "29 Apr 2026",
  oneLine:
    "The arithmetic is clean and the headline numbers reconstruct exactly. The directional diagnosis (destination-side > CPM > pricing) is well-supported. But several causal claims are stated more confidently than the evidence warrants.",
  bottomLine:
    "Listing repair (Step 1) is the highest-leverage action. Recovery to ~₹35 Meta / ~₹25 Google CPI is plausible over 12 weeks, contingent on Play Store ranking recovery. Pricing is third in importance. UAC_Conv_event_10Nov25 is probably a deliberate optimization but the quality claim hasn't been validated yet — that's Step 2's first job, not its last.",
};

// ──────────────────────────────────────────────────────────────────────────
// Confidence scoreboard — 11 claims rated 0–100
// ──────────────────────────────────────────────────────────────────────────

export type ScoreBand = "high" | "medHigh" | "medium" | "medLow" | "low";

function band(score: number): ScoreBand {
  if (score >= 90) return "high";
  if (score >= 80) return "medHigh";
  if (score >= 65) return "medium";
  if (score >= 50) return "medLow";
  return "low";
}

export const bandLabel: Record<ScoreBand, string> = {
  high: "High",
  medHigh: "Medium-High",
  medium: "Medium",
  medLow: "Medium-Low",
  low: "Low",
};

export const bandTone: Record<ScoreBand, "mint" | "sky" | "peach" | "rose"> = {
  high: "mint",
  medHigh: "mint",
  medium: "sky",
  medLow: "peach",
  low: "rose",
};

const _claims = [
  {
    claim: "Headline numbers (Meta CPI 5.16×, Google CPI 3.96×, etc.)",
    score: 98,
    note: "Arithmetic verified to within 0.2%",
  },
  {
    claim: "Phase 2 log-additive shares sum to 100%",
    score: 98,
    note: "Math reconstructs exactly",
  },
  {
    claim: "Click-to-Install is the dominant Meta lever",
    score: 88,
    note: "True, but on the like-for-like Google campaign CTR also contributes 65% — not zero",
  },
  {
    claim: "GE_UAC_High_Intent CPI rise is 'only destination-side'",
    score: 65,
    note: "Hidden CTR collapse (-66%) not explained; 'only mechanism left' overstated",
  },
  {
    claim: "Pricing is third-order driver",
    score: 75,
    note: "Real finding, but ASO inflection (14 Oct) sits inside the ₹4 baseline window",
  },
  {
    claim: "ASO listing wave is the PRIMARY DRIVER",
    score: 78,
    note: "Strongest signal in the confounder battery; 10-day timing gap unexplained",
  },
  {
    claim: "Three 'independent' measurements converge",
    score: 40,
    note: "They measure the same Play Store funnel from different vantage points — not independent",
  },
  {
    claim: "UAC_Conv_event is deeper-funnel optimization (corrected)",
    score: 70,
    note: "Internally consistent; the quality-comparison hasn't actually been computed yet",
  },
  {
    claim: "Recovery Step 1 will cut Meta CPI ~40%",
    score: 55,
    note: "Theoretical max if all else holds; ignores Play Store ranking decay risk",
  },
  {
    claim: "Lock trial price ≤ ₹29 (Step 4)",
    score: 92,
    note: "Well-supported across 5 pricing regimes",
  },
  {
    claim: "Re-pull Singular for Q2 2026 (Step 8)",
    score: 95,
    note: "Pure data hygiene, no risk",
  },
];

export const confidenceClaims = _claims.map((c) => ({
  ...c,
  band: band(c.score),
}));

// ──────────────────────────────────────────────────────────────────────────
// Methodology review — high-level pillars
// ──────────────────────────────────────────────────────────────────────────

export const methodology = [
  {
    pillar: "Question framing",
    verdict: "Sound",
    tone: "mint" as const,
    body:
      "The report decomposes 'why did CAC rise' into a 4-lever identity (CPM × CTR × Click-to-Install × Install-to-Trial). Each phase has an explicit falsification test set in advance — genuinely strong methodology.",
  },
  {
    pillar: "Data selection",
    verdict: "Partly sound, partly cherry-picked",
    tone: "peach" as const,
    body:
      "Phase 1 reconcile table shows only 7 of 12 months. The 'stable within 7% through Jan' framing hides that the gap was already widening (1.3% → 0.8% → 3.2% → 5.5%) before the Feb jump. The strictly-pure ₹4 window also overlaps the ASO change-point.",
  },
  {
    pillar: "Population definition",
    verdict: "Implicit assumption flagged",
    tone: "peach" as const,
    body:
      "'Same audience targeting' on GE_UAC_High_Intent is true at the parameter level. But UAC's bid algorithm continuously re-learns from conversion data — by Q2 2026 the effective audience is shaped by 12 months of accumulated learning. This is not a controlled experiment with frozen targeting.",
  },
  {
    pillar: "Identity assumption",
    verdict: "Verified, with one gap",
    tone: "mint" as const,
    body:
      "The CPI identity reconstructs to ₹10.94 (vs claimed ₹10.95) and ₹56.68 (vs claimed ₹56.55) — within 0.2%. However, the identity uses Meta 'link clicks' CTR — if 'click' in Click-to-Install means 'all clicks', the identity is mixing two click definitions. Worth confirming.",
  },
];

// ──────────────────────────────────────────────────────────────────────────
// Issues found — 8 issues, severity-graded
// ──────────────────────────────────────────────────────────────────────────

export type IssueSeverity = "high" | "medium" | "low";

export const issues: {
  n: number;
  severity: IssueSeverity;
  title: string;
  body: string;
  bullets?: string[];
  impact?: string;
}[] = [
  {
    n: 1,
    severity: "high",
    title: "Hidden CTR collapse on the 'like-for-like' Google campaign",
    body:
      "The report says GE_UAC_High_Intent's CPM fell 50% and CPI rose 5.13× — 'only mechanism left is destination-side'. But the implied CTR from the published numbers fell 66%, and a proper decomposition shows CTR contributed ~65% of the CPI rise — roughly the same as Click-to-Install (77%).",
    bullets: [
      "Q2 25 implied CTR: 1.682% (from CPI = CPM/1000 ÷ CTR ÷ C→I)",
      "Q2 26 implied CTR: 0.581% — a 65.5% drop",
      "Decomposition: CPM share −42%, CTR share +65%, C→I share +77%",
      "The natural explanation (bid algo bidding less aggressively → cheaper, lower-CTR placements as a downstream effect of destination-side decay) is plausible but should be stated, not hidden",
    ],
    impact:
      "The 40–60% Meta/Google CPI cut from Step 1 is too optimistic if CTR doesn't recover with C→I.",
  },
  {
    n: 2,
    severity: "high",
    title: "'Three independent measurements' overstates independence",
    body:
      "The report frames the convergence of (Meta Click-to-Install, Google Click-to-Install, Play Console visitor-to-install) as three independent measurements losing the same fraction. They are three views of the same Play Store funnel — not independent. Convergence is expected by construction, not corroborating evidence.",
    impact:
      "Soften framing to 'three vantage points all show the same drop'.",
  },
  {
    n: 3,
    severity: "medium",
    title: "ASO inflection precedes the listing-live event by 10 days",
    body:
      "CUSUM detects 14 Oct as the inflection. Nikita's 27-keyword listing went live 24 Oct. The report says 'the 27-keyword listing went live 10 days after the inflection' — but an effect cannot precede its cause. Plausible reconciliations are not stated.",
    bullets: [
      "Other _KW_CSL_ listings in the same wave likely went live earlier — the 24 Oct listing is just the most prominent",
      "Pre-publish A/B testing or staged rollout could explain the timing",
      "CUSUM is sensitive — the true mean shift might be 24 Oct ± 5 days",
    ],
    impact:
      "Without explanation, the temporal attribution is weakened.",
  },
  {
    n: 4,
    severity: "medium",
    title: "Phase 4's 'pure ₹4 baseline' contains the destination-side confound",
    body:
      "The constant-₹4 window runs 28 Apr – 16 Oct 2025. CUSUM detected the destination-side inflection on 14 Oct — inside the window. So the inside-window CPI rise (Meta 2.10×, Google 1.83×) reflects pricing held flat plus ~2 days of destination-side decay starting before the window ends.",
    impact:
      "Conclusion 'pricing is third in importance' still survives, but the magnitudes attributable to pricing-non-effect vs. destination-side baseline drift are conflated. Restating Phase 4 with a 28 Apr – 30 Sep window would be airtight.",
  },
  {
    n: 5,
    severity: "medium",
    title: "UAC corrected narrative depends on un-validated quality claim",
    body:
      "The reframed Step 2 says UAC_Conv_event_10Nov25 produces 'higher quality' users at ₹680/activated trialer. But the actual activation-rate comparison vs. the rest of the Google portfolio is the action item itself. The economics check out, but the quality claim is currently a hypothesis, not a finding.",
    impact:
      "The narrative should be honest: 'this looks like a deliberate optimization; whether the deeper signal actually selects higher-quality users is the open question.'",
  },
  {
    n: 6,
    severity: "low",
    title: "Phase 1 'sudden break' framing oversells the data",
    body:
      "The Google reconcile gap was already growing every quarter (Apr 0.8% → Jul 3.2% → Oct 5.5%). Feb's +14.7pp jump is real, but 'stable through Jan' is too clean. A regression on the daily series would tell you whether Feb is a regime change or just continuation of a power-law-ish drift.",
  },
  {
    n: 7,
    severity: "low",
    title: "Recovery Step 1 confidence 'high' overstated",
    body:
      "Returning C→I from 18% → 30% gives ~₹34 Meta CPI by my arithmetic (claimed ≤₹35) — math checks. But Play Store search rankings have algorithmic memory: even if you restore the pre-Oct listing text, you may not get the pre-Oct ranking back for weeks. The 2-week A/B is too short to detect this.",
    impact:
      "'High confidence' should be downgraded to 'medium-high, contingent on Play Store ranking recovery'.",
  },
  {
    n: 8,
    severity: "low",
    title: "Sample-size fragility on the legacy Meta cohort",
    body:
      "The 'legacy Meta workhorses' cohort = 4 campaigns. Generalizing the within-campaign decay pattern (49% → 28% on India_45583) from 4 campaigns to a structural claim about the entire portfolio is fragile. The pattern is suggestive, not statistically robust.",
  },
];

// ──────────────────────────────────────────────────────────────────────────
// Calculation spot-checks
// ──────────────────────────────────────────────────────────────────────────

export type CheckStatus = "pass" | "fail" | "info";

export const spotChecks: { check: string; result: string; status: CheckStatus }[] = [
  { check: "Meta CPI identity Q2 25",                   result: "₹10.94 vs claimed ₹10.95",          status: "pass" },
  { check: "Meta CPI identity Q2 26",                   result: "₹56.68 vs claimed ₹56.55 (rounding)", status: "pass" },
  { check: "Meta CPM share",                            result: "50.6% vs claimed 50.6%",             status: "pass" },
  { check: "Meta CTR share",                            result: "−11.4% vs claimed −11.6%",           status: "pass" },
  { check: "Meta C→I share",                            result: "61.1% vs claimed 61.0%",             status: "pass" },
  { check: "Sum of Meta shares",                        result: "100.2% (rounding)",                  status: "pass" },
  { check: "Headline ratios (5.16×, 4.17×, 3.96×, 5.16×)", result: "All exact",                        status: "pass" },
  { check: "Organic trial rate Δ",                      result: "−76.7% vs claimed −77%",             status: "pass" },
  { check: "UAC ₹/activated trialer",                   result: "₹681 vs claimed ~₹680",              status: "pass" },
  { check: "UAC ₹/install",                             result: "₹40 vs claimed ~₹40",                status: "pass" },
  { check: "Activation rate (47860/816510)",            result: "5.86% — not stated in report; worth surfacing", status: "info" },
  { check: "Recovery Step 1 Meta CPI projection",       result: "₹34.31 vs claimed ≤₹35",             status: "pass" },
  { check: "GE_UAC_High_Intent CTR (implied)",          result: "1.68% → 0.58%, −66% — NOT mentioned in report", status: "fail" },
];

// ──────────────────────────────────────────────────────────────────────────
// Suggested improvements
// ──────────────────────────────────────────────────────────────────────────

export const improvements = [
  "Add the GE_UAC_High_Intent funnel decomposition — show that on this campaign, C→I (77%) and CTR (65%) both contributed, with CPM (-42%) helping. Strengthens the destination-side thesis once you explain the CTR drop as a downstream consequence of bid-algo conservatism.",
  "Recompute Phase 4 using a clean baseline — 28 Apr – 30 Sep 2025 (excludes CUSUM inflection). Will make the pricing-isolation evidence airtight.",
  "Reconcile the 14 Oct vs 24 Oct timing — list the dates of all _KW_CSL_ listings introduced in October. If any went live ≤ 14 Oct, the cause-effect ordering is fixed.",
  "Soften the 'three independent measurements' framing to 'three vantage points on the same Play Store funnel'.",
  "Restate UAC narrative honestly — flag that the quality claim is a hypothesis, with the activation-rate comparison as the validating action.",
  "Add a confidence column to the recovery action plan — replace single-word ratings with explicit conditions for confidence (e.g., 'high confidence if Play Store ranking recovers within 4 weeks').",
  "Show all 12 months of Google reconcile, not 7 — full series will reveal whether the gap drift is power-law-ish or step-change.",
  "Add an activation rate metric (5.86% on UAC vs. unknown on rest of portfolio). This is the single number that makes or breaks the corrected UAC narrative.",
];

// ──────────────────────────────────────────────────────────────────────────
// Required caveats for stakeholders
// ──────────────────────────────────────────────────────────────────────────

export const caveats: { title: string; body: string; tone: "rose" | "peach" | "sky" | "lav" | "sand" }[] = [
  {
    title: "Step 1's 40–60% CPI cut is a partial-equilibrium estimate",
    body: "Assumes CPM, CTR, and Install-to-Trial hold constant while Click-to-Install recovers. CTR is currently down 66% on the like-for-like Google campaign and is unlikely to fully recover concurrent with C→I.",
    tone: "rose",
  },
  {
    title: "Play Store ranking memory is not modeled",
    body: "Restoring pre-Oct listings may not immediately restore pre-Oct rankings. Expect 4–8 weeks for ranking recovery, not the 2-week A/B horizon.",
    tone: "rose",
  },
  {
    title: "Phase 4 pricing isolation is contaminated by ~2 days of post-CUSUM decay",
    body: "Magnitude of contamination is small but the 'pricing is decoupled from the cliff' claim should be stated as 'pricing is decoupled from the dominant drivers' rather than mathematically proven.",
    tone: "peach",
  },
  {
    title: "UAC_Conv_event quality claim is a hypothesis, not a finding",
    body: "Step 2's first job is to actually validate it before extending to other campaigns. Don't roll this out across the Google portfolio until the activation-rate comparison is in.",
    tone: "peach",
  },
  {
    title: "Singular MMP gap is real and unresolved",
    body: "28 days of Q2 2026 numbers (1–28 Apr) lack independent attribution validation. Treat Q2 2026 platform numbers as preliminary until Step 8 is complete.",
    tone: "sky",
  },
  {
    title: "Convergence of three measurements is one piece of evidence, not three",
    body: "Meta C→I, Google C→I, and Play Console store CR all measure the same Play Store funnel. The convergence is consistent with a single-mechanism story but is not three-times-the-evidence.",
    tone: "sand",
  },
];

// What to tell vs. what NOT to tell stakeholders
export const tellNotTell = {
  tell:
    "Listing repair (Step 1) is the highest-leverage action. Recovery to ~₹35 Meta / ~₹25 Google CPI is plausible over 12 weeks, contingent on Play Store ranking recovery. Pricing is third in importance. UAC_Conv_event_10Nov25 is probably a deliberate optimization but the quality claim hasn't been validated yet — that's Step 2's first job, not its last.",
  notYet: [
    "That destination-side is the only mechanism (CTR is also moving)",
    "That the three measurements are independent (they aren't)",
    "That the listing rollback will deterministically deliver the headline impact (depends on Play Store ranking recovery, which is not modeled)",
  ],
};
